---

- name: "Config Gaming PC Hyperv Server"
  hosts: hyperv 

  tasks:
  - name: "Install Vagrant"
    chocolatey.chocolatey.win_chocolatey:
      name: vagrant
      state: present

  - name: "Install Neovim"
    chocolatey.chocolatey.win_chocolatey:
      name: neovim
      state: present
